name: JS Tests
on: push

jobs:
  test-add:
    needs: lint
    runs-on: ubuntu latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
       
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run
  lint:
  #needs: Test-add
    runs-on: ubuntu latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
       
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.14'

    - name: Install dependencies
      run: npm install

    - name: Run linter
      run: npm run Lint
  